security:
    password_hashers:
        App\Entity\Profil: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Profil
                property: cin

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtAuthenticator
            stateless: true

        
            
            access_denied_url: /login 

    access_control:
        - { path: ^/dashboard/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard/medecin, roles: ROLE_MEDECIN }
        - { path: ^/dashboard/patient, roles: ROLE_PATIENT }