security:
    password_hashers:
        App\Entity\Profil: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Profil
                property: cin

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtAuthenticator
            stateless: true
