parameters:
    jwt_secret: '%env(JWT_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $logger: '@logger'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Controllers
    App\Controller\LoginController:
        arguments:
            $jwtSecret: '%jwt_secret%'

    App\Controller\Dashboard\MedecinDashboardController:
        arguments:
            $jwtSecret: '%jwt_secret%'

    # Authenticator
    App\Security\JwtAuthenticator:
        arguments:
            $jwtSecret: '%jwt_secret%'

    # Event listeners
    App\EventListener\AdminInitListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    App\EventListener\RoleRedirectListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }